[build-system]
requires = [
    "setuptools>=61",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "forbiddenfp"
version = "0.8.5"
dependencies = [
    "forbiddenfruit",
    "typing_extensions",
]
